jobs = [
     {"type": 'allocations',
     "days": 30,
     "hours": 23,
     "minutes": 59,
     "seconds": 59,
     "step": 24,
     "rows": 1000000,
     "query": "allocations",
     "return_value": "allocations",
     "output": "outputs",
     "upload": False,
     "drive_folder" : "1yY7hYt4Wnzygcqw-evdKcn3qgIq18k2e",
     "sheet_id": "1JwtNbtszGLkbCUd6o--nNr_gQMxS2Lgpft7Y8zrDnGY",
     "filename" : "allocations"
    },
    {"type": 'global',
     "days": 60,
     "hours": 23,
     "minutes": 59,
     "seconds": 59,
     "step": 24,
     "rows":60,
     "query": "global",
     "return_value": "graphNetwork",
     "output": "outputs",
     "upload": "sheet",
     "drive_folder" : "1cwpLRHyS32qrXBaMxAOfMvNWRYyFas7a",
     "sheet_id": "1gPAudaLeuZIymSBC78nob8BISwvWIXWcjbPVmapEivI",
     "filename" : "global"
    },
    {"type": 'subgraphs',
     "days": 30,
     "hours": 23,
     "minutes": 59,
     "seconds": 59,
     "step": 24,
     "rows": 1000000,
     "query": "main",
     "return_value": "subgraphVersions",
     "output": "outputs",
     "upload": "sheet",
     "drive_folder" : "1yY7hYt4Wnzygcqw-evdKcn3qgIq18k2e",
     "sheet_id": "1JwtNbtszGLkbCUd6o--nNr_gQMxS2Lgpft7Y8zrDnGY",
     "filename" : "subgraphs"
    }
]

columns_in = {}
columns_in['allocations'] = {
    'allocatedTokens' : 'allocated_tokens',
    'closedAtBlockNumber': 'closed_at_block',
    'delegationFees' : 'delegation_fees',
    'subgraphDeployment_id' : 'deployment_id',
    'queryFeesCollected' : 'QF_collected',
    'subgraphDeployment_versions_id': 'version_id'  
}

columns_in['main'] = {
    'subgraph_active' : 'active',
    'id': 'version_id',
    'subgraph_displayName' : 'display_name',
    'subgraph_owner_id': 'owner_id',
    'subgraphDeployment_curatorFeeRewards' : 'curator_rewards_total',
    'subgraphDeployment_id' : 'deployment_id',
    'subgraphDeployment_indexingDelegatorRewardAmount' : 'delegator_rewards_total',
    'subgraphDeployment_indexingIndexerRewardAmount': 'indexer_rewards_total',
    'subgraphDeployment_network_id': 'newtwork_id',
    'subgraphDeployment_pricePerShare': 'price_per_share',
    'subgraphDeployment_queryFeesAmount' : 'QF_total',
    'subgraphDeployment_reserveRatio': 'reserve_ratio',
    'subgraphDeployment_signalAmount': 'shares',
    'subgraphDeployment_signalledTokens': 'signal',
    'subgraphDeployment_stakedTokens': 'stake',
    'subgraph_createdAt': 'created_at'
}

columns_in['global'] = {
    'curationPercentage': 'curation_pct',
    'delegationRatio': 'delegation_ratio',
    'totalTokensStaked': 'stake',
    'totalDelegatedTokens': 'delegation',
    'totalTokensAllocated': 'allocation',
    'totalQueryFees': 'QF_total',
    'totalCuratorQueryFees': 'curator_rewards_total',
    'totalIndexingIndexerRewards': 'indexer_rewards_total',
    'totalIndexingDelegatorRewards': 'delegator_rewards_total',
    'totalTokensSignalled': 'signal',
}

rename = {}

columns_out = {}

columns_out['30d_dump'] = [
    'displayName',
    'subgraph_id',
    'version_id',
    'deployment_id',
    'owner_id',
    'network_id',
    'block',
    'blockDate'
    'blockTime',
    'active',
    'curatorFeeRewards',
    'indexerRewardAmount',
    'delegatorRewardAmount',
    'queryFeesAmount',
    'signalAmount',
    'signalledTokens',
    'pricePerShare',
    'stakedTokens',
    'createdDate',
]
columns_out['global'] = [
    'date',
    'stake',
    'signal',
    'delegation',
    'allocation',
    'QF_total',
    'indexer_rewards_total',
    'delegator_rewards_total',
    'curator_rewards_total',
    'stake_change',
    'stake_change_7d',
    'stake_change_30d',
    'signal_change',
    'signal_change_7d',
    'signal_change_30d',
    'delegation_change',
    'delegation_change_7d',
    'delegation_change_30d',
    'allocation_change',
    'allocation_change_7d',
    'allocation_change_30d',
    'QF',
    'QF_7d',
    'QF_30d',
    'indexer_rewards',
    'indexer_rewards_7d',
    'indexer_rewards_30d',
    'delegator_rewards',
    'delegator_rewards_7d',
    'delegator_rewards_30d',
    'curator_rewards',
    'curator_rewards_7d',
    'curator_rewards_30d',
    'signal_per_stake',
    'QF30D_per_signal',
    'indexer_apr_30d_estimate',
    'delegator_apr_30d_estimate',
    'curator_apr_30d_estimate'
]

columns_out['subgraphs'] = [
    'subgraph_id', 
    'display_name',
    'block', 
    'date', 
    'created_at', 
    'active',
    'QF_total',
    'shares',
    'signal',
    'stake',
    'curator_rewards_total',
    'delegator_rewards_total',
    'indexer_rewards_total',
    'price_per_share',
    'QF',
    'signal_change',
    'stake_change',
    'shares_change',
    'price_change',
    'curator_rewards',
    'indexer_rewards',
    'delegator_rewards',
    'QF_7d',
    'QF_14d',
    'QF_30d',
    'signal_change_7d',
    'signal_change_14d',
    'signal_change_30d',
    'signal_7d_MA',
    'signal_14d_MA',
    'signal_30d_MA',
    'stake_change_7d',
    'stake_change_14d',
    'stake_change_30d',
    'stake_7d_MA',
    'stake_14d_MA',
    'stake_30d_MA',
    'shares_change_7d',
    'shares_change_14d',
    'shares_change_30d',
    'shares_7d_MA',
    'shares_14d_MA',
    'shares_30d_MA',
    'price_change_7d',
    'price_change_14d',
    'price_change_30d',
    'price_7d_MA',
    'price_14d_MA',
    'price_30d_MA',
    'curator_rewards_7d',
    'curator_rewards_14d',
    'curator_rewards_30d',
    'indexer_rewards_7d',
    'indexer_rewards_14d',
    'indexer_rewards_30d',
    'delegator_rewards_7d',
    'delegator_rewards_14d',
    'delegator_rewards_30d',
    'curator_rewards_per_signal_7d',
    'curator_rewards_per_signal_14d',
    'curator_rewards_per_signal_30d',
    'indexer_rewards_per_stake_7d',
    'indexer_rewards_per_stake_14d',
    'indexer_rewards_per_stake_30d',
    'signal_per_stake',
    'curator_apr_30d_estimate',
    'indexer_apr_30d_estimate',
    'price_growth_7d',
    'price_growth_14d',
    'price_growth_30d',
    #'curator_rewards_per_share_30d',
    #'curator_rewards_per_share_squared_30d',
    #'price_per_reward_30d'
    ]
columns_out['allocations'] = [
    'subgraph_id',
    'id',
    'status',
    'block',
    'allocated_tokens',
    'delegation_fees',
    'QF_collected',
    'closed_at_block',
    'version_id',
    'deployment_id',
    ]

columns_sheet = {}
columns_sheet['subgraphs'] = [
    'subgraph_id', 
    'display_name',
    'date', 
    'curator_apr_30d_estimate',
    'indexer_apr_30d_estimate',
    'QF_30d',
    'shares',
    'signal',
    'stake',
    'signal_per_stake',
    'curator_rewards_total',
    'delegator_rewards_total',
    'indexer_rewards_total',
    'price_per_share',
    'QF_total',
    'signal_change_7d',
    'signal_change_14d',
    'signal_change_30d',
    'price_growth_7d',
    'price_growth_14d',
    'price_growth_30d',
    ]

columns_sheet['global'] = [
    'date',
    'stake',
    'signal',
    'delegation',
    'allocation',
    'QF_total',
    'indexer_rewards_total',
    'delegator_rewards_total',
    'curator_rewards_total',
    'stake_change',
    'stake_change_7d',
    'stake_change_30d',
    'signal_change',
    'signal_change_7d',
    'signal_change_30d',
    'delegation_change',
    'delegation_change_7d',
    'delegation_change_30d',
    'allocation_change',
    'allocation_change_7d',
    'allocation_change_30d',
    'QF',
    'QF_7d',
    'QF_30d',
    'indexer_rewards',
    'indexer_rewards_7d',
    'indexer_rewards_30d',
    'delegator_rewards',
    'delegator_rewards_7d',
    'delegator_rewards_30d',
    'curator_rewards',
    'curator_rewards_7d',
    'curator_rewards_30d',
    'signal_per_stake',
    'QF30D_per_signal',
    'indexer_apr_30d_estimate',
    'delegator_apr_30d_estimate',
    'curator_apr_30d_estimate'
]
